import { Inter } from "next/font/google";
import "./globals.css";
import nav from "./Componentes/nav";
import footer from "./Componentes/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fitnet Force",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
      <nav/> 
        {children}
      <footer/>
        </body>
    </html>
  );
}
