import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Componentes/nav";
import Footer from "./Componentes/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fitnet Force",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
      <Nav />
      
        <main className="centrar">
        {children}
        </main>
      
      <Footer />
        </body>
    </html>
  );
}
